version: "3"

services:
  backend:
    build:
      context: .
      args:
        REQUIREMENTS: requirements-dev.txt
    depends_on:
      - mailhog
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - EMAIL_URL=smtp://localhost:1025
    volumes:
      - ./:/app
    command: /bin/sh -c "wait-for-it.sh db:5432 -- ./manage.py migrate && ./manage.py runserver 0.0.0.0:80"
